blank_issues_enabled: false
contact_links:
  - name: ğŸ“š Docs
    url: /docs
    about: Checkout repo-file-sync-action's documentation.
  - name: â“ Ask a Question
    url: /discussions/new?category=q-a
    about: Ask the community for help